# Generated by Django 4.1.7 on 2023-03-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
