# Generated by Django 4.2.2 on 2023-06-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_cart_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_stripe_key',
            field=models.CharField(default='', max_length=50),
        ),
    ]
