# Generated by Django 4.1.7 on 2023-03-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_computer_computer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='manufacturer',
            field=models.CharField(default='', max_length=20),
        ),
    ]
