# Generated by Django 4.1.7 on 2023-03-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_laptop_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='ram',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='disk',
            field=models.IntegerField(default=256),
        ),
    ]
