# Generated by Django 4.1.7 on 2023-03-12 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_computer_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='computer_id',
        ),
    ]
