# Generated by Django 4.1.7 on 2023-03-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_computer_computer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='image',
            field=models.ImageField(default='', upload_to='home/images'),
        ),
    ]
